### ISSUE TITLE
support for shorts broken?

### ISSUE THREAD

**Issue by mryko** [RobertWesner/YouTube-Play-All#1]
just used it today, it works for videos perfectly but not shorts  

for example
https://www.youtube.com/@zurcsan/shorts  
 
I tried fixing it with the following code:  
```
        if (( !window.location.pathname.endsWith('/videos') && !window.location.pathname.endsWith('/shorts') ) || document.querySelector('.play-all-button')) {
```

the button now appears:  
![image](https://github.com/RobertWesner/YouTube-Play-All/assets/109264271/671cd9fc-42f9-40c3-a438-f95865e5df47)

but the link it creates is not valid:  
![image](https://github.com/RobertWesner/YouTube-Play-All/assets/109264271/7bb71925-51ea-4d44-9a81-e3d5ff90987d)

**Comment by RobertWesner** [comment]
Shorts work differently from videos and are not supported _yet_. I am not aware of a playlist for just shorts as of now, but from what I can see just clicking the latest short in the shorts tab lets you play all by the channel. As I don't use shorts myself, I'll need to do some digging first.

**Comment by RobertWesner** [comment]
Shorts are now playable with the lists `UUSH` (Short videos) and `UUPS` (Popular short videos)
