### ISSUE TITLE
Play All Random

### ISSUE THREAD

**Issue by RobertWesner** [RobertWesner/YouTube-Play-All#13]
This will be an addition to the current functionality by providing a "random play" feature. Should be simple enough when using the default latest playlists and journaling watched videos. Accessible with a new switch next to Latest / Popular, by adding Random in the videos section. There you can see the current journal and start or resume your random play session.

**Comment by RobertWesner** [comment]
Feature is now in beta!

Install by clicking [here](https://github.com/RobertWesner/YouTube-Play-All/raw/13-play-all-random/script.user.js)

**Comment by RobertWesner** [comment]
Currently all already watched **randomly played** videos will be excluded from playing again.
The cache can be cleared by clicking the bin:
![image](https://github.com/user-attachments/assets/6a70d408-4d6b-42a3-a384-459e16dabf03)

**Comment by RobertWesner** [comment]
(Mobile probably does not work at this moment, it is untested)

**Comment by RobertWesner** [comment]
UI was changed to an x-mark instead of the bin to clear the random cache.
![image](https://github.com/user-attachments/assets/44b657c8-09d1-4a04-bf1f-c919d036ead6)

Randomness is now actually random, not limited to the 100 visible videos YouTube provides in the playlist widget.

**Comment by bolach** [comment]
I'm in! I did not saw any reference that i was installing a beta code, maybe add something like the title or some first line with this notice?

I had to verify twice that i was installing the beta version and not the stable version

**Comment by RobertWesner** [comment]
@bolach Thank you for the feedback. From now on beta versions will have the `-beta` suffix to distinguish them from stable releases, visisble in line 4 (`@version`). The dev tools wil also inform you if using a non-stable version.

```js
// ==UserScript==
// @name            YouTube Play All
// @description     Adds the Play-All-Button to the videos, shorts, and live sections of a YouTube-Channel
// @version         20241028-0-beta
                               ^
                               '- beta version
```

![image](https://github.com/user-attachments/assets/1677139a-0e2e-4cde-9981-80a086902466)

**Comment by RobertWesner** [comment]
The commits just added are caused by a rebase onto the main branch since additional Chrome compatibility was merged in #14.

**Comment by bolach** [comment]
I tested the Play Random button with a channel i never saw before. It opened a new window and started playing from newest to the oldest:
![mercury_nL0vgYhXa8](https://github.com/user-attachments/assets/65f91435-7a7a-4fcf-ac6e-d7e645fce5e3)

**Comment by RobertWesner** [comment]
I opened the [same channel](https://www.youtube.com/@MelissaDiamondsAakinlife97/videos) it seems autoplay doesn't play random anymore. I'll look into it.

Skipping with the "Next Video" Button to the right of Play/Pause (make sure its random when hovering) works still.

Notes for further implementation:
- [ ] `Shift + N` is not randomized yet
- [ ] Miniplayer controls are not randomized
- [ ] Timestamp-Parameter is not cleared (Relevant for [YouTube O Clock](https://github.com/RobertWesner/YouTube-O-Clock)
- [ ] index-Parameter is not set correctly

**Comment by RobertWesner** [comment]
I suspect the issue is the detection:
```js
if (progressState.current / progressState.duration >= 0.999) {
    markWatched(videoId);
    playNextRandom();
}
```

The videos are fairly short, I previously tested on longer content. Presumably 0.999 is far too narrow for the ~90s videos.

**Comment by RobertWesner** [comment]
@bolach the issue should be fixed now. Please update to 20241028-2-beta.

**Comment by bolach** [comment]
I tested with a new random channel
I can already see by the created playlist that the videos are still by the order newest-oldest

[channel](https://www.youtube.com/@vesikielell)
![mercury_sFvam9IkBU](https://github.com/user-attachments/assets/1babecae-9d74-46f3-b7b6-3b9771a0aeed)
![mercury_ojyl2d4HU2](https://github.com/user-attachments/assets/d7f0be54-a4a7-4210-80a6-71d755c284d4)
))

**Comment by RobertWesner** [comment]
The playlist itself will always list them in order. They will still be selected randomly. This is intentional. Random play occurs when skipping or reaching the end of the video. The first video of the random play is the newest but will automatically skip if it was previously watched in random play.

**Comment by RobertWesner** [comment]
The first video in random play will no longer be the most recent. It will jump to a random video.

The playlist will display a notice now:
![image](https://github.com/user-attachments/assets/118c3532-02cd-4692-af86-16eb521e01ec)
Hovering over it still allows for manual selection of a video.

**Comment by bolach** [comment]
First tests seems to be working @RobertWesner , i will continue using it.

1.  Questions

1.1 - At the moment, the 2 buttons, Play all and Play Random are one the page /channel/videos. It is possible to be on /channel homepage?

1.2 - This random button will play all the videos, even if the channel has several thousands?

1.3 - It will not repeat the same video on the channel? Or random is truly random and it can play several times the same video before a never watched appears?

1.4 - My chromium based browsers auto start playing the video. The geckos not. This is something related to the browsers or it was just me?

**Comment by RobertWesner** [comment]
Glad everything is working now.

1. The buttons are intentionally on the videos sections as they also exist for shorts and streams in their respective sections. Someone else has made a plugin based on my documentation to make many playlists available in the home section. See [here](https://greasyfork.org/en/scripts/492119-youtube-all-videos-playlists-yavp). The usersrcipt is meant to be close to the original "Play All" button we had in the 201Xs.

2. Yes, it has a local storage for all known videos which updates dynamically the more you watch, it will select randomly from that storage. Storage updates from the 100 videos visible in the playlist widget on the watch page. The further you go down the list, the more it will store, eventually collecting all. At the beginning it has a slight bias towards the most recent ~100 videos since those are the only ones available but quickly fills up after one or two videos have been played randomly.

3. Said storage remembers watched videos. If you disable random play by clicking the badge (see [here](https://github.com/RobertWesner/YouTube-Play-All/issues/13#issuecomment-2409035490) the cache will be cleared and previously watched videos will not remembered. If you instead close the tab or just close your browser, it will keep the watched videos the next time you click "Play Random".

4. This is an intended feature of Firefox, unrelated to the script. [You can change that behavior](https://support.mozilla.org/bm/questions/1260002).

**Comment by bolach** [comment]
Thank you for that @RobertWesner 
I will continue testing. I will report if something fails

**Comment by bolach** [comment]
I did not change anything, but for some reason, I can't see play all or random buttons anymore. It is just me?
![brave_GFJqdN1AGT](https://github.com/user-attachments/assets/d2b43b90-2267-4eb1-970f-f7639411e738)

**Comment by RobertWesner** [comment]
@bolach this is probably related to #5 since the channel has only very few videos and doesnt show the latest/popular buttons.

**Comment by RobertWesner** [comment]
@bolach have you encountered any more problems? If everything is working fine, I will release this tomorrow.

**Comment by bolach** [comment]
> @bolach have you encountered any more problems? If everything is working fine, I will release this tomorrow.

@RobertWesner everything working fine here

**Comment by RobertWesner** [comment]
Perfect, I'll set everything up to have this available to the public. Thanks again for all the testing! Could not have gotten this far with just my tests.

**Comment by bolach** [comment]
> Perfect, I'll set everything up to have this available to the public. Thanks again for all the testing! Could not have gotten this far with just my tests.

Of course you could do it. You did all the work and deserve the credit and gratitude for sharing this with everyone!
